# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d12c7020711766c19404b0b2a564162ae5c90bdef6f2a82054c2a8b5b20c9aa7ceba229c9fcce362ad815051d5ef0da2df75bb2314f0eaceefea0f3ff5ad4a23

test:
  secret_key_base: 88da9f54a450f783f5ac282a18777f0e85d16703502391b7f0df0822f5bb4c33d002ed3f4ddb9db0c5829aa75f7182d998d8f955b0e8ff22d1fdcb1a6998913f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
